version: '3'

services:
  node:
    build: .
    ports:
    - "8000:8000"
  mongo:
    image: mongo
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: '1234'
    ports:
    - "27017:27017"
    volumes:
    - ./data:/data/db
volumes:
  local-mongo: